name: Java CI with Maven

# Controla cuándo se ejecutará el workflow.
on:
  push:
    branches: [ "main", "master" ]  # Se ejecuta al hacer push a main
  pull_request:
    branches: [ "main", "master" ]  # Se ejecuta al crear un PR hacia main

jobs:
  # Este es el nombre de "build".
  build:
    # Especifica el tipo de máquina virtual donde se ejecutará (última versión de Ubuntu).
    runs-on: ubuntu-latest

    # Los pasos representan la secuencia de tareas a ejecutar.
    steps:
      # 1. PASO CHECKOUT
      # Acción estándar para clonar tu repositorio dentro de la máquina virtual,
      # para que el workflow pueda acceder.
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. PASO SETUP-JAVA
      # Acción para instalar y configurar la versión de Java
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'                     
          distribution: 'temurin'                
          cache: maven                           

      # 3. PASO BUILD (CONSTRUIR)
      # Ejecuta el comando de Maven para compilar el código y empaquetarlo.
      # El comando 'clean verify' limpia, compila, ejecuta tests y verifica la integridad del paquete.
      - name: Construir con Maven (Build)
        run: mvn clean verify
